I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenes_script/scene_3.rpy", line 22, in script
    call screen narration("You and Doctor A go into an office. You see a woman dressed in a nurse outfit working in front of the desk. She seems quite enthusiastic despite the amount of work that had piled in front of her")
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
TypeError: 'int' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenes_script/scene_3.rpy", line 22, in script
    call screen narration("You and Doctor A go into an office. You see a woman dressed in a nurse outfit working in front of the desk. She seems quite enthusiastic despite the amount of work that had piled in front of her")
  File "/Volumes/renpy-7.5.3-sdk/renpy-7.5.3-sdk/renpy/ast.py", line 2232, in execute
    self.call("execute")
  File "/Volumes/renpy-7.5.3-sdk/renpy-7.5.3-sdk/renpy/ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Volumes/renpy-7.5.3-sdk/renpy-7.5.3-sdk/renpy/statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/Volumes/renpy-7.5.3-sdk/renpy-7.5.3-sdk/renpy/exports.py", line 3181, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/Volumes/renpy-7.5.3-sdk/renpy-7.5.3-sdk/renpy/ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Volumes/renpy-7.5.3-sdk/renpy-7.5.3-sdk/renpy/display/core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Volumes/renpy-7.5.3-sdk/renpy-7.5.3-sdk/renpy/display/core.py", line 3754, in interact_core
    new_widget=layers_root)
TypeError: 'int' object is not callable

Darwin-21.6.0-x86_64-i386-64bit x86_64
Ren'Py 7.5.3.22090809
BetaGame 1.0
Wed Oct 19 23:45:36 2022
